### ISSUE TITLE
Work in progress?

### ISSUE THREAD

**Issue by markrendle** [rsocket/rsocket-net#1]
Is this being worked on? With the new [System.IO.Pipelines](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/) API this would be fantastic for .NET Core microservices.

If nobody's working on it I might have a hack at it.

**Comment by rdegnan** [comment]
Yes, RSocket.NET is actively being worked on. As of today we have an initial protocol implementation and WebSocket transport using System.IO.Pipelines. Much more coming soon, but if you have an interest in using this your comments/contributions would be very welcome -- feel free to reach out to me directly and I can share our roadmap.
