### ISSUE TITLE
Missing interfaces and class in DotNet RSocket.Core Nuget package version 1.0.0

### ISSUE THREAD

**Issue by clrsky** [rsocket/rsocket-net#15]
@OlegDokuka , we observed that a new version 1.0.0 was available from nuget on 23rd july 2020
It was observed that few classes and interface available in 0.2.3 are not available in the new version
For ex: IRSocketChannel and RSocketOptions are not longer available

## Expected Behavior
From yesterdays code merge and **discussion done with Reetesh Agarwal's team** ,we were expecting that the same changes would be available related to PR https://github.com/rsocket/rsocket-net/pull/11

## Actual Behavior
Some of the  interfaces and classes are no longer available and code seems to contain few different method and classes.
Please confirm if its from the same source and 1.0.0 is the intended version to be used.

Attaching a comparison screen shot for reference: 
![image](https://user-images.githubusercontent.com/22585629/88411927-69dd9680-cdf6-11ea-859f-3fd1d4373cda.png)

**Comment by clrsky** [comment]
@OlegDokuka , updated the discussion details and the team leader involved for more clarity. 
Kindly help us in clarification of the above query to help us move forward.

**Comment by OlegDokuka** [comment]
this is a wrong, old version which was added accidentally and should not be used. The appropriate one is 0.2.3. 

Please use classes and code structure from 0.2.3

**Comment by clrsky** [comment]
Thank you @OlegDokuka
