### ISSUE TITLE
strong name signing needed for version 0.2.3

### ISSUE THREAD

**Issue by clrsky** [rsocket/rsocket-net#18]
## Motivation
Strong name signing will encourage more users to use the RSocket core library so that it can be used by projects which use strong name signing

## Desired solution
Create a strong name key and sign the RSocket core dll

## Considered alternatives
Tried signing locally but due to virality of strong name signing it requires properly signed dlls.
## Additional context

Steps:
1. Generating the strong name file using visual studio 2017 cmd prompt and sn tool:
sn -k RSocketStrongName.snk

![image](https://user-images.githubusercontent.com/22585629/90513684-a5614b80-e17d-11ea-986e-a0873aee794b.png)

2. Enabling strong name signing via visual studio: In project properties use signing , refer below screen shot for reference.
![image](https://user-images.githubusercontent.com/22585629/90513359-24a24f80-e17d-11ea-803d-5f08b0865f64.png)

3. Verification of the signature: sn -v RSocket.Core.dll
![image](https://user-images.githubusercontent.com/22585629/90513870-f40ee580-e17d-11ea-966a-5f0dd79bead4.png)

**Comment by OlegDokuka** [comment]
Hi @clrsky!

Is it possible to do the same in OsX? 
I have spend a while looking for similar thing, but it seem there is no support for this paltfor.

Cheers,
Oleh

**Comment by clrsky** [comment]
Hi @OlegDokuka 
I am using a windows machine, looks like no support for mac based on initial analysis.
Attaching a zip of the same for reference. Hope it helps.
[RSocketStrongName.zip](https://github.com/rsocket/rsocket-net/files/5090531/RSocketStrongName.zip)

**Comment by OlegDokuka** [comment]
fixed

**Comment by clrsky** [comment]
cool , just verified RSocket.core.dll is strong name signed now 
![image](https://user-images.githubusercontent.com/22585629/90688266-d3cd4c80-e28b-11ea-8063-2e4680887989.png)

**Comment by clrsky** [comment]
but digital signature is missing .. 
![image](https://user-images.githubusercontent.com/22585629/90688338-f2334800-e28b-11ea-8411-18472ab11ba3.png)

Can we try digital signing using the cert obtained using visual studio? help can be found at this link: 
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-sign-application-and-deployment-manifests?view=vs-2019
