### ISSUE TITLE
There is a useful version for websocket & unity

### ISSUE THREAD

**Issue by smallp** [rsocket/rsocket-net#35]
The client of websocket in this repository cannot work properly, as websocket don't have frame length.
So if you want to use rsocket with websocket, try [this](https://github.com/smallp/rsocket-net).

**Comment by theperm** [comment]
where did the repo go?

**Comment by smallp** [comment]
It used to have one. But later I add some feature for my compony, so I can't publish it now.

**Comment by theperm** [comment]
Thanks for the update. That's not good. Could you keep the previous version
up before you add features instead of removing it?

And why doesn't you company give back to open source instead of just
benefiting. Surely you haven't built any domain specific features into the
client?

**Comment by smallp** [comment]
Because this client is far away from production using.
I fixed some bugs and because my version is only for websocket nor tcp, so I can't create a pr. Thats's why I add this issue.
But after I add some feature, I found more bugs and realized my version can't work well either. So I delete it. It will take me lots of time to get it back.
BTW: I even remove Reactive. That's so crazy.
